### ISSUE TITLE
Dealing with wrong inputs

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2lqb#12]
Hi @HellenNamulinda 

Revising the model, I've noticed that the way you have structured the code from the original source prevents the automated check to identify smiles that cannot be processed.
In particular, the my_model function is prepared to take a list of smiles, parse it and keep only the ones that are correct, but since you are calling this function on each single smiles, it loses its function and the model is unable to process a file if a SMILES is not correct.
Can you please revise the code in main.py and reformat it so the my_model is called upon the whole list of input smiles? and these are not silenced:
```
    #df=pd.concat([df_right,df_error],axis=0) 
    #df=df.fillna(-1)
    #print(df)
```
Probably we need to start by changing this function:

```
with open(input_file, "r") as f:
    reader = csv.reader(f)
    next(reader)  # skip header
    smiles_list = [r[0] for r in reader]   
    with open(output_file, "a") as f: 
        writer = csv.writer(f) 
        for s in range(len(smiles_list)):
            output = run_model([smiles_list[s]])
            writer.writerow(output)
```

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
I pushed the changes and created a pull request [here ](https://github.com/ersilia-os/eos2lqb/pull/13)

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

What is the status of this, did we ask someone to test with wrong molecules?

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
I had not told anyone to test the model. But as I mentioned in the [pull request](https://github.com/ersilia-os/eos2lqb/pull/13#issue-1755284987) and also @DhanshreeA commented about in last week's meeting. 
Ersilia just crashes if one of the inputs is wrong, with this error
```
    mol = self.Chem.MolFromSmiles(smiles)
TypeError: No registered converter was able to produce a C++ rvalue of type std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > from this Python object of type NoneType
```

I also thought @miquelduranfrigola was going looking into this

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

Have you had a look into Ersilia's code itself? Please remember to paste the full errors, using the -v flag, so that you can better understand what is happening. In this case, I have tested and the error I get (attached) is in this file:
```
ersilia/ersilia/utils/identifiers/compound.py", line 114, in encode
    mol = self.Chem.MolFromSmiles(smiles)
```
If you go and look into the specific function, you will see there is a conditional to test that this conversion is happening:        
```
else:
            mol = self.Chem.MolFromSmiles(smiles)
            if mol is None:
                raise Exception(
                    "The SMILES string: %s is not valid or could not be converted to an InChIKey"
                    % smiles
                )
```
If you try manually, you will see how the wrong SMILES is returning `mol = None`, which should then raise the exception and let ersilia continue. When you run it from the `run.sh` is this the case you say, and the issue is only with the CLI? What is the output you get when you run it from run.sh? 

```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("CCCCCC")
>>> print(mol)
<rdkit.Chem.rdchem.Mol object at 0x7f56d4da7a30>
>>> mol = Chem.MolFromSmiles("CCXXC")
[09:19:35] SMILES Parse Error: syntax error while parsing: CCXXC
[09:19:35] SMILES Parse Error: Failed parsing SMILES 'CCXXC' for input: 'CCXXC'
>>> print(mol)
None
```

Please try to go to this level of explanation and looking when you encounter an error, it will help us point you better towards a solution
[eos2lqb.log](https://github.com/ersilia-os/eos2lqb/files/11830126/eos2lqb.log)

**Comment by GemmaTuron** [comment]
This has been solved in Ersilia's main codebase.
See this commit https://github.com/ersilia-os/ersilia/commit/028dbf2bc3f7a759422e3a60145263a00a8e923e
