### ISSUE TITLE
Eliminate generated files in eos2lqb

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2lqb#16]
Hi @HellenNamulinda !

I have seen that when I run the eos2lqb (aside from the issue with wrong smiles) two files are generated at some point in the pipeline: 
`finger.csv`
`smiles.smi`

Could you identify where are they generated and add a piece of code that removes those generated files at the end of the run?

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
Sorry, I forgot to remove this earlier.
these intermediate files were being generated in hob_predict.py.
```
        smi_path='smiles.smi'
        smile_file =open(smi_path,'w')
        for smile in smiles_right:
            smile=smile.replace("'", '')+'\n'
            smile_file.write(smile)
        smile_file.close()
        smi_path='smiles.smi'
        finger_path='finger.csv
```
So in [this PR](https://github.com/ersilia-os/eos2lqb/pull/17), I added the code to remove them before returning the fingers
    ```
    finger=pd.read_csv(finger_path)
    os.remove(smi_path)
    os.remove(finger_path)
    return finger
```
