### ISSUE TITLE
BioModel Discussion Issue for eos2lqb

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos2lqb#20]
**Summary !!!**

- **BioModel Name**: Wei2022 - HobPre: accurate prediction of human oral bioavailability for small molecules

- **BioModel Tag**: Machine learning model, Ersilia

- **Metadata Comments**: 
This model classified it's data as positive and negative based on bioavailability percentage. This annotation is the closest to a positive class - http://purl.obolibrary.org/obo/NCIT_C64356. I think this better suits than active, what do you think @GemmaTuron ? or we can assume it's classified as active bioavailability compounds or inactive.

- **Contributor**:
> 
 | roles             | Names | 
 | :---------------- | :------: | 
 | Curator        |   @Zainab-ik   | 
 | Code contributor      |   @HellenNamulinda        | 
 | Reviewer       |   @GemmaTuron    | 

- **Curation status** :  manually curated

- **Annotation file**: [here](https://docs.google.com/spreadsheets/d/1-AM5Mi_U-zDwRmY36GUQ2_ApxMuGWbK-UfIBHDQxDs4/edit?usp=drive_link)

**Comment by GemmaTuron** [comment]
With the context of drug discovery we can simply use the "active" "inactive" terms
