### ISSUE TITLE
Give probabilities as output

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2lqb#3]
The model currently outputs High or Low, I'd prefer to get a probability value instead @HellenNamulinda

**Comment by HellenNamulinda** [comment]
Hello @GemmaTuron,
I have worked on this and created a pull request.

When using Ersilia CLI for a single compound, the first value is the probability of a compound having high oral bioavailability (HOB >20%) and the second value is the probability of a compound having high oral bioavailability (HOB >50%).
```
{
    "input": {
        "key": "CJCSPKMFHVPWAR-UHFFFAOYSA-N",
        "input": "CC(N)(Cc1ccc(O)c(O)c1)C(=O)O",
        "text": "CC(N)(Cc1ccc(O)c(O)c1)C(=O)O"
    },
    "output": {
        "outcome": [
            0.8987280273905661,
            0.47943911035866493
        ]
    }
}

```

**Comment by GemmaTuron** [comment]
Perfect @HellenNamulinda 

The PR passed all the checks so I have merged it!

**Comment by HellenNamulinda** [comment]
Thank you!
I have fetched the model and ran predictions on [eml_canonical.csv](https://github.com/ersilia-os/eos2lqb/files/11128508/eml_canonical.csv).
This is the output file; 
[output.csv](https://github.com/ersilia-os/eos2lqb/files/11159797/output.csv)

**Comment by GemmaTuron** [comment]
Fantastic! I'll close this as completed many thanks for your contribution @HellenNamulinda !
